config/routes.rb
Rails.application.routes.draw do
  resources :solve_computations
  resources :zeroes_computations
  resources :log_computations
  resources :tangent_computations
  resources :def_integral_computations
  resources :trig_computations
  resources :computations
  root to: 'computations#index'
end

app/models/tangent_computation.rb
class TangentComputation < ApplicationRecord
end

app/controllers/tangent_computations_controller.rb
class TangentComputationsController < ApplicationController
  before_action :set_tangent_computation, only: %i[ show edit update destroy ]
  before_action :get_api

  # GET /tangent_computations or /tangent_computations.json
  def index
    @tangent_computations = TangentComputation.all
  end

  # GET /tangent_computations/1 or /tangent_computations/1.json
  def show
  end

  # GET /tangent_computations/new
  def new
    @tangent_computation = TangentComputation.new
  end

  # GET /tangent_computations/1/edit
  def edit
  end

  # POST /tangent_computations or /tangent_computations.json
  def create
    @tangent_computation = TangentComputation.new(tangent_computation_params)
    @tangent_computation.result = @client.tangent(tangent_computation_params[:point], tangent_computation_params[:expression])["result"]

    respond_to do |format|
      if @tangent_computation.save
        format.html { redirect_to @tangent_computation, notice: "Tangent computation was successfully created." }
        format.json { render :show, status: :created, location: @tangent_computation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tangent_computation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tangent_computations/1 or /tangent_computations/1.json
  def update
    @tangent_computation.result = @client.tangent(tangent_computation_params[:point], tangent_computation_params[:expression])["result"]
    respond_to do |format|
      if @tangent_computation.update(tangent_computation_params)
        format.html { redirect_to @tangent_computation, notice: "Tangent computation was successfully updated." }
        format.json { render :show, status: :ok, location: @tangent_computation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tangent_computation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tangent_computations/1 or /tangent_computations/1.json
  def destroy
    @tangent_computation.destroy
    respond_to do |format|
      format.html { redirect_to tangent_computations_url, notice: "Tangent computation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_api
    @client = NewtonAPI::V2::Client.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tangent_computation
      @tangent_computation = TangentComputation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tangent_computation_params
      params.require(:tangent_computation).permit(:point, :expression)
    end
end

app/helpers/tangent_computations_helper.rb
module TangentComputationsHelper
end

app/views/tangent_computations/_form.html.erb
<%= form_with(model: tangent_computation) do |form| %>
  <% if tangent_computation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tangent_computation.errors.count, "error") %> prohibited this tangent_computation from being saved:</h2>

      <ul>
        <% tangent_computation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :point %>
    <%= form.text_field :point %>
  </div>

  <div class="field">
    <%= form.label :expression %>
    <%= form.text_field :expression %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tangent_computations/edit.html.erb
<h1>Editing Tangent Computation</h1>

<%= render 'form', tangent_computation: @tangent_computation %>

<%= link_to 'Show', @tangent_computation %> |
<%= link_to 'Back', tangent_computations_path %>

app/views/tangent_computations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tangent Computations</h1>

<table>
  <thead>
    <tr>
      <th>Point</th>
      <th>Expression</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tangent_computations.each do |tangent_computation| %>
      <tr>
        <td><%= tangent_computation.point %></td>
        <td><%= tangent_computation.expression %></td>
        <td><%= tangent_computation.result %></td>
        <td><%= link_to 'Show', tangent_computation %></td>
        <td><%= link_to 'Edit', edit_tangent_computation_path(tangent_computation) %></td>
        <td><%= link_to 'Destroy', tangent_computation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tangent Computation', new_tangent_computation_path %>

app/views/tangent_computations/new.html.erb
<h1>New Tangent Computation</h1>

<%= render 'form', tangent_computation: @tangent_computation %>

<%= link_to 'Back', tangent_computations_path %>

app/views/tangent_computations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Point:</strong>
  <%= @tangent_computation.point %>
</p>

<p>
  <strong>Expression:</strong>
  <%= @tangent_computation.expression %>
</p>

<p>
  <strong>Result:</strong>
  <%= @tangent_computation.result %>
</p>

<%= link_to 'Edit', edit_tangent_computation_path(@tangent_computation) %> |
<%= link_to 'Back', tangent_computations_path %>