config/routes.rb
Rails.application.routes.draw do
  resources :solve_computations
  resources :zeroes_computations
  resources :log_computations
  resources :tangent_computations
  resources :def_integral_computations
  resources :trig_computations
  resources :computations
  root to: 'computations#index'
end

app/models/computation.rb
class Computation < ApplicationRecord
end

app/controllers/computations_controller.rb
class ComputationsController < ApplicationController
  before_action :set_computation, only: %i[ show edit update destroy ]
  before_action :get_api

  # GET /computations or /computations.json
  def index
    @computations = Computation.all
  end

  # GET /computations/1 or /computations/1.json
  def show
  end
 
  # GET /computations/new
  def new
    @computation = Computation.new
  end

  # GET /computations/1/edit
  def edit
  end

  # POST /computations or /computations.json
  def create
    @computation = Computation.new(computation_params)
    @computation.result = @client.compute(computation_params[:function], computation_params[:expression])["result"]
    respond_to do |format|
      if @computation.save
        format.html { redirect_to @computation, notice: "Computation was successfully created." }
        format.json { render :show, status: :created, location: @computation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @computation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computations/1 or /computations/1.json
  def update
    @computation.result = @client.compute(computation_params[:function], computation_params[:expression])["result"]
    respond_to do |format|
      if @computation.update(computation_params)
        format.html { redirect_to @computation, notice: "Computation was successfully updated." }
        format.json { render :show, status: :ok, location: @computation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @computation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computations/1 or /computations/1.json
  def destroy
    @computation.destroy
    respond_to do |format|
      format.html { redirect_to computations_url, notice: "Computation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_api
    @client = NewtonAPI::V2::Client.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computation
      @computation = Computation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def computation_params
      params.require(:computation).permit(:function, :expression)
    end
end

app/helpers/computations_helper.rb
module ComputationsHelper
end

app/views/computations/_form.html.erb
<%= form_with(model: computation) do |form| %>
  <% if computation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(computation.errors.count, "error") %> prohibited this computation from being saved:</h2>

      <ul>
        <% computation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :function %>
    <%= form.text_field :function %>
  </div>

  <div class="field">
    <%= form.label :expression %>
    <%= form.text_field :expression %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/computations/edit.html.erb
<h1>Editing Computation</h1>

<%= render 'form', computation: @computation %>

<%= link_to 'Show', @computation %> |
<%= link_to 'Back', computations_path %>

app/views/computations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Computations</h1>

<table>
  <thead>
    <tr>
      <th>Function</th>
      <th>Expression</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @computations.each do |computation| %>
      <tr>
        <td><%= computation.function %></td>
        <td><%= computation.expression %></td>
        <td><%= link_to 'Show', computation %></td>
        <td><%= link_to 'Edit', edit_computation_path(computation) %></td>
        <td><%= link_to 'Destroy', computation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Computation', new_computation_path %>

app/views/computations/new.html.erb
<h1>New Computation</h1>

<%= render 'form', computation: @computation %>

<%= link_to 'Back', computations_path %>

app/views/computations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Function:</strong>
  <%= @computation.function %>
</p>

<p>
  <strong>Expression:</strong>
  <%= @computation.expression %>
</p>

<p>
  <strong>Result:</strong>
  <%= @computation.result %>
</p>

<%= link_to 'Edit', edit_computation_path(@computation) %> |
<%= link_to 'Back', computations_path %>