config/routes.rb
Rails.application.routes.draw do
  resources :solve_computations
  resources :zeroes_computations
  resources :log_computations
  resources :tangent_computations
  resources :def_integral_computations
  resources :trig_computations
  resources :computations
  root to: 'computations#index'
end

app/models/solve_computation.rb
class SolveComputation < ApplicationRecord
end

app/controllers/solve_computations_controller.rb
class SolveComputationsController < ApplicationController
  before_action :set_solve_computation, only: %i[ show edit update destroy ]
  before_action :get_api

  # GET /solve_computations or /solve_computations.json
  def index
    @solve_computations = SolveComputation.all
  end

  # GET /solve_computations/1 or /solve_computations/1.json
  def show
  end

  # GET /solve_computations/new
  def new
    @solve_computation = SolveComputation.new
  end

  # GET /solve_computations/1/edit
  def edit
  end

  # POST /solve_computations or /solve_computations.json
  def create
    @solve_computation = SolveComputation.new(solve_computation_params)
    @solve_computation.result = @client.solve(solve_computation_params[:left_hand], solve_computation_params[:right_hand])["result"]

    respond_to do |format|
      if @solve_computation.save
        format.html { redirect_to @solve_computation, notice: "Solve computation was successfully created." }
        format.json { render :show, status: :created, location: @solve_computation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @solve_computation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solve_computations/1 or /solve_computations/1.json
  def update
    @solve_computation.result = @client.solve(solve_computation_params[:left_hand], solve_computation_params[:right_hand])["result"]
    respond_to do |format|
      if @solve_computation.update(solve_computation_params)
        format.html { redirect_to @solve_computation, notice: "Solve computation was successfully updated." }
        format.json { render :show, status: :ok, location: @solve_computation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @solve_computation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solve_computations/1 or /solve_computations/1.json
  def destroy
    @solve_computation.destroy
    respond_to do |format|
      format.html { redirect_to solve_computations_url, notice: "Solve computation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_api
    @client = NewtonAPI::V2::Client.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solve_computation
      @solve_computation = SolveComputation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def solve_computation_params
      params.require(:solve_computation).permit(:left_hand, :right_hand)
    end
end

app/helpers/solve_computations_helper.rb
module SolveComputationsHelper
end

app/views/solve_computations/_form.html.erb
<%= form_with(model: solve_computation) do |form| %>
  <% if solve_computation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(solve_computation.errors.count, "error") %> prohibited this solve_computation from being saved:</h2>

      <ul>
        <% solve_computation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :left_hand %>
    <%= form.text_field :left_hand %>
  </div>

  <div class="field">
    <%= form.label :right_hand %>
    <%= form.text_field :right_hand %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/solve_computations/edit.html.erb
<h1>Editing Solve Computation</h1>

<%= render 'form', solve_computation: @solve_computation %>

<%= link_to 'Show', @solve_computation %> |
<%= link_to 'Back', solve_computations_path %>

app/views/solve_computations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Solve Computations</h1>

<table>
  <thead>
    <tr>
      <th>Left hand</th>
      <th>Right hand</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solve_computations.each do |solve_computation| %>
      <tr>
        <td><%= solve_computation.left_hand %></td>
        <td><%= solve_computation.right_hand %></td>
        <td><%= solve_computation.result %></td>
        <td><%= link_to 'Show', solve_computation %></td>
        <td><%= link_to 'Edit', edit_solve_computation_path(solve_computation) %></td>
        <td><%= link_to 'Destroy', solve_computation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Solve Computation', new_solve_computation_path %>

app/views/solve_computations/new.html.erb
<h1>New Solve Computation</h1>

<%= render 'form', solve_computation: @solve_computation %>

<%= link_to 'Back', solve_computations_path %>

app/views/solve_computations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Left hand:</strong>
  <%= @solve_computation.left_hand %>
</p>

<p>
  <strong>Right hand:</strong>
  <%= @solve_computation.right_hand %>
</p>

<p>
  <strong>Result:</strong>
  <%= @solve_computation.result %>
</p>

<%= link_to 'Edit', edit_solve_computation_path(@solve_computation) %> |
<%= link_to 'Back', solve_computations_path %>